http:
  port: 17000
  adminPort: 17001
  connectorType: nonblocking

elasticsearch:
  hosts:
  - localhost
  cluster: elasticsearch
  tableNamePrefix: foxtrot

hbase:
  secure : false
  tableName: foxtrot
  hbaseZookeeperQuorum: localhost
  hbaseZookeeperClientPort: 2181

cluster:
  name: foxtrot
  disableMulticast: true
  members: ["localhost:5701", "localhost:5702"]

logging:
  level: INFO

deletionconfig:
  active: true
  interval: 86400
  initialdelay: 60

restrictionsConfig:
  limitupperbound: -1  # Use -1 for no limit
  betweenduration: 4d     # Leave blank for no limit
  lastduration: 2d       # Leave blank for no limit
  fieldsize: 100          # Use -1 for no limit